import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import MainBoard from "../components/MainBoard";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <MainBoard />
      </Main>
    </div>
  );
};

export default Home;

const Main = styled.main`
  width: 100%;
  background-color: #fafafa;
`;
